# Generated by Django 6.0.6 on 2026-06-20 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "codcategoria",
                    models.AutoField(
                        db_column="CodCategoria", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomecategoria",
                    models.CharField(db_column="NomeCategoria", max_length=40),
                ),
                (
                    "descrizione",
                    models.CharField(
                        blank=True, db_column="Descrizione", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "CATEGORIA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "idcliente",
                    models.AutoField(
                        db_column="IdCliente", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=30)),
                ("cognome", models.CharField(db_column="Cognome", max_length=30)),
                ("email", models.CharField(db_column="Email", max_length=50)),
                (
                    "recapitotelefonico",
                    models.CharField(db_column="RecapitoTelefonico", max_length=15),
                ),
            ],
            options={
                "db_table": "CLIENTE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Dipendente",
            fields=[
                (
                    "iddipendente",
                    models.AutoField(
                        db_column="IdDipendente", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=30)),
                ("cognome", models.CharField(db_column="Cognome", max_length=30)),
                ("email", models.CharField(db_column="Email", max_length=50)),
                (
                    "recapitotelefonico",
                    models.CharField(db_column="RecapitoTelefonico", max_length=15),
                ),
                (
                    "codicefiscale",
                    models.CharField(db_column="CodiceFiscale", max_length=16),
                ),
            ],
            options={
                "db_table": "DIPENDENTE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Fila",
            fields=[
                (
                    "codfila",
                    models.IntegerField(
                        db_column="CodFila", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tariffagiornaliera",
                    models.DecimalField(
                        db_column="TariffaGiornaliera", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "tariffastagionale",
                    models.DecimalField(
                        db_column="TariffaStagionale", decimal_places=2, max_digits=8
                    ),
                ),
            ],
            options={
                "db_table": "FILA",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Fornitore",
            fields=[
                (
                    "partitaiva",
                    models.CharField(
                        db_column="PartitaIVA",
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=50)),
                ("email", models.CharField(db_column="Email", max_length=50)),
                ("indirizzo", models.CharField(db_column="Indirizzo", max_length=60)),
                (
                    "recapitotelefonico",
                    models.CharField(db_column="RecapitoTelefonico", max_length=15),
                ),
            ],
            options={
                "db_table": "FORNITORE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Mansione",
            fields=[
                (
                    "codmansione",
                    models.AutoField(
                        db_column="CodMansione", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomemansione",
                    models.CharField(
                        db_column="NomeMansione", max_length=40, unique=True
                    ),
                ),
                (
                    "descrizione",
                    models.CharField(
                        blank=True, db_column="Descrizione", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "MANSIONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "codprodotto",
                    models.AutoField(
                        db_column="CodProdotto", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomeprodotto",
                    models.CharField(db_column="NomeProdotto", max_length=40),
                ),
                (
                    "quantitàmagazzino",
                    models.IntegerField(db_column="QuantitàMagazzino"),
                ),
                ("quantitàminima", models.IntegerField(db_column="QuantitàMinima")),
                ("codcategoria", models.IntegerField(db_column="CodCategoria")),
            ],
            options={
                "db_table": "PRODOTTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Proprietario",
            fields=[
                (
                    "idproprietario",
                    models.AutoField(
                        db_column="IdProprietario", primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(db_column="Nome", max_length=30)),
                ("cognome", models.CharField(db_column="Cognome", max_length=30)),
                ("email", models.CharField(db_column="Email", max_length=50)),
                (
                    "recapitotelefonico",
                    models.CharField(db_column="RecapitoTelefonico", max_length=15),
                ),
                ("password", models.CharField(db_column="Password", max_length=255)),
            ],
            options={
                "db_table": "PROPRIETARIO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TariffeNoleggio",
            fields=[
                (
                    "tiponoleggio",
                    models.CharField(
                        db_column="TipoNoleggio",
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prezzo",
                    models.DecimalField(
                        db_column="Prezzo", decimal_places=2, max_digits=8
                    ),
                ),
            ],
            options={
                "db_table": "TARIFFE_NOLEGGIO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "iddipendente",
                        "data",
                        "orainizio",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("iddipendente", models.IntegerField(db_column="IdDipendente")),
                ("data", models.DateField(db_column="Data")),
                ("orainizio", models.TimeField(db_column="OraInizio")),
                ("orafine", models.TimeField(db_column="OraFine")),
                ("codmansione", models.IntegerField(db_column="CodMansione")),
            ],
            options={
                "db_table": "TURNO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Abbonamento",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "codfila",
                        "numombrellone",
                        "anno",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codfila", models.IntegerField(db_column="CodFila")),
                ("numombrellone", models.IntegerField(db_column="NumOmbrellone")),
                ("anno", models.TextField(db_column="Anno")),
                (
                    "prezzo",
                    models.DecimalField(
                        db_column="Prezzo", decimal_places=2, max_digits=8
                    ),
                ),
                ("sconto", models.FloatField(db_column="Sconto")),
                ("pagamento", models.CharField(db_column="Pagamento", max_length=1)),
                (
                    "idcliente",
                    models.ForeignKey(
                        db_column="IdCliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "ABBONAMENTO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ombrellone",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "codfila",
                        "numombrellone",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numombrellone", models.IntegerField(db_column="NumOmbrellone")),
                (
                    "codfila",
                    models.ForeignKey(
                        db_column="CodFila",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.fila",
                    ),
                ),
            ],
            options={
                "db_table": "OMBRELLONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Ordine",
            fields=[
                (
                    "codordine",
                    models.AutoField(
                        db_column="CodOrdine", primary_key=True, serialize=False
                    ),
                ),
                ("dataordine", models.DateField(db_column="DataOrdine")),
                ("consegnaprevista", models.DateField(db_column="ConsegnaPrevista")),
                (
                    "dataconsegna",
                    models.DateField(blank=True, db_column="DataConsegna", null=True),
                ),
                (
                    "partitaiva",
                    models.ForeignKey(
                        db_column="PartitaIVA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.fornitore",
                    ),
                ),
                (
                    "idproprietario",
                    models.ForeignKey(
                        db_column="IdProprietario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.proprietario",
                    ),
                ),
            ],
            options={
                "db_table": "ORDINE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DettaglioOrdine",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "codordine",
                        "partitaiva",
                        "codprodotto",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("partitaiva", models.CharField(db_column="PartitaIVA", max_length=11)),
                ("codprodotto", models.IntegerField(db_column="CodProdotto")),
                ("quantità", models.IntegerField(db_column="Quantità")),
                (
                    "prezzoalmomento",
                    models.DecimalField(
                        db_column="PrezzoAlMomento", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "codordine",
                    models.ForeignKey(
                        db_column="CodOrdine",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.ordine",
                    ),
                ),
            ],
            options={
                "db_table": "DETTAGLIO_ORDINE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Prenotazione",
            fields=[
                (
                    "codprenotazione",
                    models.AutoField(
                        db_column="CodPrenotazione", primary_key=True, serialize=False
                    ),
                ),
                ("datainizio", models.DateField(db_column="DataInizio")),
                ("datafine", models.DateField(db_column="DataFine")),
                (
                    "prezzo",
                    models.DecimalField(
                        db_column="Prezzo", decimal_places=2, max_digits=8
                    ),
                ),
                ("sconto", models.FloatField(db_column="Sconto")),
                (
                    "note",
                    models.CharField(
                        blank=True, db_column="Note", max_length=255, null=True
                    ),
                ),
                ("pagamento", models.CharField(db_column="Pagamento", max_length=1)),
                ("codfila", models.IntegerField(db_column="CodFila")),
                ("numombrellone", models.IntegerField(db_column="NumOmbrellone")),
                (
                    "idcliente",
                    models.ForeignKey(
                        db_column="IdCliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.cliente",
                    ),
                ),
            ],
            options={
                "db_table": "PRENOTAZIONE",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Catalogo",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "partitaiva",
                        "codprodotto",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prezzounitario",
                    models.DecimalField(
                        db_column="PrezzoUnitario", decimal_places=2, max_digits=8
                    ),
                ),
                (
                    "partitaiva",
                    models.ForeignKey(
                        db_column="PartitaIVA",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.fornitore",
                    ),
                ),
                (
                    "codprodotto",
                    models.ForeignKey(
                        db_column="CodProdotto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.prodotto",
                    ),
                ),
            ],
            options={
                "db_table": "CATALOGO",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="NoleggioLettino",
            fields=[
                (
                    "codnoleggio",
                    models.AutoField(
                        db_column="CodNoleggio", primary_key=True, serialize=False
                    ),
                ),
                ("data", models.DateField(db_column="Data")),
                ("quantità", models.IntegerField(db_column="Quantità")),
                (
                    "prezzototale",
                    models.DecimalField(
                        db_column="PrezzoTotale", decimal_places=2, max_digits=8
                    ),
                ),
                ("pagamento", models.CharField(db_column="Pagamento", max_length=1)),
                (
                    "idcliente",
                    models.ForeignKey(
                        db_column="IdCliente",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.cliente",
                    ),
                ),
                (
                    "tiponoleggio",
                    models.ForeignKey(
                        db_column="TipoNoleggio",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="gestionaleStabilimento.tariffenoleggio",
                    ),
                ),
            ],
            options={
                "db_table": "NOLEGGIO_LETTINO",
                "managed": True,
            },
        ),
    ]
